"""
vis_anchor_pool_maya.py — Export anchor-pool predicted joints as Maya scripts.

For each identity in `nfs_features_seg/`, applies anchor pooling using the
ICT-derived (anchor, offset), then writes:
  - {out_dir}/template_{id}.obj
  - {out_dir}/pred_anchor_joints_{id}.py     Maya skeleton (Maya init blue + anchor pred green)

Usage:
    python vis_anchor_pool_maya.py \
        --rig_path maya_rig/hybrid \
        --feat_dir nfs_features_seg \
        --datasets ict mf \
        --data_basedir /data/sihun \
        --ids ict_000 m--20180226--0000--6674443--GHS

In Maya:
    File > Import > template_*.obj
    Window > Script Editor > Python > open .py and run
    → blue = Maya init, green = anchor-pool prediction
"""
import os
import sys
import argparse
import numpy as np
import torch

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, '..', '..'))
sys.path.insert(0, _HERE)
sys.path.insert(0, _ROOT)
sys.path.insert(0, os.path.join(_ROOT, 'tools', 'precompute'))  # extract_nfs_feat
from utils.rig_loader import load_rig
from utils.anchor_pool import compute_bind_pos
from extract_nfs_feat import (
    load_templates_ict, load_templates_mf, load_templates_coma, load_templates_biwi,
)


_MAYA_TEMPLATE = '''"""Auto-generated by vis_anchor_pool_maya.py
Two skeleton hierarchies:
  - {prefix}_maya_init  (BLUE):  rig.bind_pos (Maya GT, ICT-aligned)
  - {prefix}_pred       (GREEN): anchor-pool predicted bind_pos for this identity
"""
import maya.cmds as cmds


_MAYA_POS  = {maya_positions!r}
_PRED_POS  = {pred_positions!r}
_NAMES     = {joint_names!r}
_PARENTS   = {parent_names!r}
_PREFIX    = {prefix!r}


def _build(label, positions, color_rgb):
    grp = cmds.group(em=True, n=f'{{_PREFIX}}_{{label}}')
    for name, parent in zip(_NAMES, _PARENTS):
        jname = f'{{_PREFIX}}_{{label}}_{{name}}'
        if parent is None:
            cmds.select(grp)
        else:
            cmds.select(f'{{_PREFIX}}_{{label}}_{{parent}}')
        cmds.joint(p=positions[name], n=jname)
        cmds.setAttr(f'{{jname}}.overrideEnabled', 1)
        cmds.setAttr(f'{{jname}}.overrideColor', color_rgb)
    cmds.select(cl=True)
    return grp


def main():
    _build('maya_init', _MAYA_POS, 6)   # blue
    _build('pred',      _PRED_POS, 14)  # green
    print(f'Created: {{_PREFIX}}_maya_init (blue)  +  {{_PREFIX}}_pred (green)')


main()
'''


def _write_maya_script(save_path, prefix, joint_names, parent_names,
                       maya_positions, pred_positions):
    maya_dict = {n: list(p) for n, p in zip(joint_names, maya_positions)}
    pred_dict = {n: list(p) for n, p in zip(joint_names, pred_positions)}
    content = _MAYA_TEMPLATE.format(
        prefix=prefix,
        joint_names=joint_names,
        parent_names=parent_names,
        maya_positions=maya_dict,
        pred_positions=pred_dict,
    )
    with open(save_path, 'w') as f:
        f.write(content)


def _write_obj(save_path, verts, faces):
    with open(save_path, 'w') as f:
        for v in verts:
            f.write(f'v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n')
        for tri in faces:
            f.write(f'f {tri[0]+1} {tri[1]+1} {tri[2]+1}\n')


def _load_templates(dataset, data_basedir):
    if dataset == 'ict':  return load_templates_ict()
    if dataset == 'mf':   return load_templates_mf(data_basedir)
    if dataset == 'coma': return load_templates_coma()
    if dataset == 'biwi': return load_templates_biwi()
    raise ValueError(f'unknown dataset: {dataset}')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--rig_path', type=str, required=True)
    ap.add_argument('--feat_dir', type=str, default='nfs_features_seg')
    ap.add_argument('--datasets', nargs='+', default=['ict', 'mf'],
                    choices=['ict', 'mf', 'coma', 'biwi'])
    ap.add_argument('--data_basedir', type=str, default='/data/sihun')
    ap.add_argument('--ids', nargs='*', default=None,
                    help='Specific id_names to export (default: a few representative ones)')
    ap.add_argument('--anchors_npy', type=str, default=None)
    ap.add_argument('--offsets_npy', type=str, default=None)
    ap.add_argument('--temperature', type=float, default=0.1)
    ap.add_argument('--out_dir', type=str, default=None)
    ap.add_argument('--device', type=str, default='cuda:0')
    args = ap.parse_args()

    device = torch.device(args.device)
    anchors_path = args.anchors_npy or os.path.join(args.rig_path, 'joint_anchors.npy')
    offsets_path = args.offsets_npy or os.path.join(args.rig_path, 'joint_offsets.npy')
    out_dir = args.out_dir or os.path.join(args.rig_path, 'anchor_vis_maya')
    os.makedirs(out_dir, exist_ok=True)

    anchor = torch.tensor(np.load(anchors_path), dtype=torch.float32, device=device)
    offset = torch.tensor(np.load(offsets_path), dtype=torch.float32, device=device)
    print(f'anchor: {tuple(anchor.shape)}  offset: {tuple(offset.shape)}')

    rig = load_rig(args.rig_path, device='cpu')
    joint_names  = list(rig.joint_names)
    parent_idx   = rig.parent_idx.cpu().numpy().tolist()
    parent_names = [joint_names[p] if p >= 0 else None for p in parent_idx]
    maya_pos_all = rig.bind_pos.cpu().numpy().tolist()

    # Default: pick a few representative IDs
    default_pick = {
        'ict': ['ict_000', 'ict_005', 'ict_012'],
        'mf':  None,   # filled below
        'coma': None,
    }

    for ds in args.datasets:
        templates = _load_templates(ds, args.data_basedir)
        verts_by_id = {name: verts for verts, _f, name in templates}
        faces_by_id = {name: faces for _v, faces, name in templates}
        all_ids = list(verts_by_id.keys())

        if args.ids:
            ids_to_use = [i for i in args.ids if i in verts_by_id]
        else:
            picks = default_pick.get(ds)
            if picks is None:
                picks = all_ids[:3]
            ids_to_use = [i for i in picks if i in verts_by_id]

        if not ids_to_use:
            continue

        print(f'\n── {ds}: {len(ids_to_use)} ids ──')
        for id_name in ids_to_use:
            feat_path = os.path.join(args.feat_dir, f'{id_name}_nfs_feat.npy')
            if not os.path.exists(feat_path):
                print(f'  [skip] no NFS feat for {id_name}')
                continue

            verts_np = verts_by_id[id_name].astype(np.float32)
            faces_np = faces_by_id[id_name].astype(np.int32)
            feat_np  = np.load(feat_path).astype(np.float32)

            verts = torch.tensor(verts_np, dtype=torch.float32, device=device)
            feat  = torch.tensor(feat_np,  dtype=torch.float32, device=device)
            assert feat.shape[0] == verts.shape[0], \
                f'{id_name}: feat V={feat.shape[0]} vs mesh V={verts.shape[0]}'

            with torch.no_grad():
                bind_pos = compute_bind_pos(verts, feat, anchor, offset,
                                             temperature=args.temperature,
                                             offset_frame='world')
            pred_np = bind_pos.cpu().numpy()
            shifts  = np.linalg.norm(pred_np - np.array(maya_pos_all), axis=-1)

            prefix = id_name.replace('--', '_').replace('-', '_')
            obj_path = os.path.join(out_dir, f'template_{prefix}.obj')
            py_path  = os.path.join(out_dir, f'pred_anchor_joints_{prefix}.py')
            _write_obj(obj_path, verts_np, faces_np)
            _write_maya_script(py_path, prefix, joint_names, parent_names,
                               maya_pos_all, pred_np.tolist())

            print(f'  {id_name}: V={verts_np.shape[0]}  '
                  f'shift_from_maya median={np.median(shifts):.4f}  max={shifts.max():.4f}')
            print(f'    {obj_path}')
            print(f'    {py_path}')

    print(f'\nDone. Output dir: {out_dir}')
    print('Maya: import .obj  →  Script Editor (Python)  →  open & run .py')


if __name__ == '__main__':
    main()
