"""
vis_aug_bind_pose_maya.py — Export caricaturized (augmented) per-id mesh +
augmented per-id bind pose as Maya-ready scripts, for visual verification.

For each id in --datasets:
  - {out_dir}/template_{id}_orig.obj   : original per-id neutral mesh
  - {out_dir}/template_{id}_aug.obj    : caricaturized augmented mesh
  - {out_dir}/aug_joints_{id}.py       : Maya skeleton creation script
                                          • {id}_orig  (BLUE) : original per-id bind pose
                                          • {id}_aug   (GREEN): augmented per-id bind pose

The per-id bind poses come from:
  original: nfs_features_seg/{id}_bind_pos_landmark.npy   (Phase B v3 cache)
  augmented: nfs_features_seg_aug/{id}_aug_bind_pos_landmark.npy

Usage:
    python tools/vis/vis_aug_bind_pose_maya.py \
        --datasets ict:2,mf:12 \
        --aug_dir nfs_features_seg_aug \
        --feat_dir nfs_features_seg \
        --out_dir maya_rig/hybrid/aug_bind_pose_vis

In Maya:
    1. File → Import → template_{id}_orig.obj and template_{id}_aug.obj
    2. Window → Script Editor → Python → run aug_joints_{id}.py
"""
import os
import sys
import argparse
import pickle
import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, '..', '..')))

from utils.rig_loader import load_rig


_MAYA_TEMPLATE = '''"""Auto-generated by vis_aug_bind_pose_maya.py
Two skeleton hierarchies in Maya:
  - {prefix}_orig (BLUE) : original per-id bind pose (Phase B v3 cache)
  - {prefix}_aug  (GREEN): caricaturized augmented per-id bind pose
Import the corresponding template_*_orig.obj and template_*_aug.obj first.
"""
import maya.cmds as cmds


_ORIG_POS = {orig_positions!r}
_AUG_POS  = {aug_positions!r}
_NAMES    = {joint_names!r}
_PARENTS  = {parent_names!r}
_PREFIX   = {prefix!r}


def _build(label, positions, color_rgb):
    grp_name = f'{{_PREFIX}}_{{label}}'
    if cmds.objExists(grp_name):
        cmds.delete(grp_name)
    grp = cmds.group(em=True, n=grp_name)
    for name, parent in zip(_NAMES, _PARENTS):
        jname = f'{{_PREFIX}}_{{label}}_{{name}}'
        if parent is None:
            cmds.select(grp)
        else:
            cmds.select(f'{{_PREFIX}}_{{label}}_{{parent}}')
        cmds.joint(p=positions[name], n=jname)
        cmds.setAttr(f'{{jname}}.overrideEnabled', 1)
        cmds.setAttr(f'{{jname}}.overrideColor', color_rgb)
    cmds.select(cl=True)
    return grp


def main():
    _build('orig', _ORIG_POS, 6)    # blue
    _build('aug',  _AUG_POS,  14)   # green
    print(f'Created: {{_PREFIX}}_orig (blue, original per-id) + '
          f'{{_PREFIX}}_aug (green, caricaturized)')


main()
'''


def _write_obj(path, V, F):
    with open(path, 'w') as f:
        for v in V:
            f.write(f'v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n')
        for tri in F:
            f.write(f'f {int(tri[0]) + 1} {int(tri[1]) + 1} {int(tri[2]) + 1}\n')


def _load_template(dataset, identity_idx, data_basedir='/data/sihun'):
    if dataset == 'ict':
        from utils.remesh_utils import ICT_face_model
        import torch
        ict_model = ICT_face_model()
        iden_vecs = torch.load('ict_face_pt/ict_id_vecs_test.pt', weights_only=False).numpy()
        id_coeff = iden_vecs[identity_idx]
        id_disps = ict_model.get_id_disp(id_coeff).squeeze()
        verts = (ict_model.neutral_verts + id_disps).astype(np.float32)
        faces = ict_model.faces.astype(np.int32)
        return verts, faces, f'ict_{identity_idx:03d}'
    if dataset == 'mf':
        pkl = os.path.join(data_basedir, 'multiface_align', 'mf_templates.pkl')
        if not os.path.exists(pkl):
            pkl = os.path.join(data_basedir, 'pca', 'multiface_align', 'mf_templates.pkl')
        with open(pkl, 'rb') as f:
            t = pickle.load(f)
        keys = [k for k in t if k != 'face']
        faces = np.array(t['face'], dtype=np.int32)
        id_name = keys[identity_idx]
        verts = np.array(t[id_name], dtype=np.float32)
        return verts, faces, id_name
    raise ValueError(f'unknown dataset: {dataset}')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--datasets', type=str, default='ict:2,mf:12',
                    help='Comma-separated ds:idx pairs.')
    ap.add_argument('--rig_path', type=str, default='maya_rig/hybrid')
    ap.add_argument('--feat_dir', type=str, default='nfs_features_seg',
                    help='Original per-id bind pose cache dir.')
    ap.add_argument('--aug_dir', type=str, default='nfs_features_seg_aug',
                    help='Augmented per-id bind pose + mesh cache dir.')
    ap.add_argument('--out_dir', type=str, default='maya_rig/hybrid/aug_bind_pose_vis')
    ap.add_argument('--data_basedir', type=str, default='/data/sihun')
    args = ap.parse_args()

    rig = load_rig(args.rig_path, device='cpu')
    joint_names = list(rig.joint_names)
    parent_idx_np = rig.parent_idx.cpu().numpy().tolist()
    parent_names  = [joint_names[p] if p >= 0 else None for p in parent_idx_np]
    # process_order — parents built before children in Maya
    if hasattr(rig, 'process_order'):
        _po = rig.process_order.cpu().numpy().tolist()
    else:
        _po = list(range(len(joint_names)))
    names_ordered   = [joint_names[i]  for i in _po]
    parents_ordered = [parent_names[i] for i in _po]

    os.makedirs(args.out_dir, exist_ok=True)

    for spec in args.datasets.split(','):
        spec = spec.strip()
        if not spec: continue
        ds_key, _idx = spec.split(':')
        ds_key = ds_key.strip(); id_idx = int(_idx)
        V_orig, F, id_name = _load_template(ds_key, id_idx, args.data_basedir)
        print(f'\n── {ds_key}:{id_idx} ({id_name}) ──')

        # Load augmented mesh + bind poses
        aug_v_path  = os.path.join(args.aug_dir,  f'{id_name}_aug.npy')
        aug_bp_path = os.path.join(args.aug_dir,  f'{id_name}_aug_bind_pos_landmark.npy')
        orig_bp_path = os.path.join(args.feat_dir, f'{id_name}_bind_pos_landmark.npy')
        for p in (aug_v_path, aug_bp_path, orig_bp_path):
            if not os.path.exists(p):
                print(f'  [skip] missing {p}'); continue
        if not all(os.path.exists(p) for p in (aug_v_path, aug_bp_path, orig_bp_path)):
            continue

        V_aug = np.load(aug_v_path).astype(np.float32)
        bp_orig = np.load(orig_bp_path).astype(np.float32)
        bp_aug  = np.load(aug_bp_path).astype(np.float32)

        # Stats
        d_mesh = np.linalg.norm(V_aug - V_orig, axis=-1)
        d_bind = np.linalg.norm(bp_aug - bp_orig, axis=-1)
        print(f'  mesh ‖Δ‖: mean={d_mesh.mean():.4f} max={d_mesh.max():.4f}')
        print(f'  bind ‖Δ‖: mean={d_bind.mean():.4f} max={d_bind.max():.4f}')

        prefix = f'{ds_key}_{id_idx:03d}'

        # Write OBJs
        orig_obj = os.path.join(args.out_dir, f'template_{prefix}_orig.obj')
        aug_obj  = os.path.join(args.out_dir, f'template_{prefix}_aug.obj')
        _write_obj(orig_obj, V_orig, F)
        _write_obj(aug_obj,  V_aug,  F)

        # Write Maya skeleton script
        orig_d = {n: bp_orig[i].tolist() for i, n in enumerate(joint_names)}
        aug_d  = {n: bp_aug[i].tolist()  for i, n in enumerate(joint_names)}
        py = _MAYA_TEMPLATE.format(
            orig_positions=orig_d, aug_positions=aug_d,
            joint_names=names_ordered, parent_names=parents_ordered,
            prefix=prefix,
        )
        py_path = os.path.join(args.out_dir, f'aug_joints_{prefix}.py')
        with open(py_path, 'w') as f:
            f.write(py)
        print(f'  saved: {orig_obj}, {aug_obj}, {py_path}')

    print(f'\nDone. Output dir: {args.out_dir}')


if __name__ == '__main__':
    main()
