"""
vis_per_id_bind_pos_landmark.py — Verify per-id bind_pose GT (Phase B).

Loads {id_name}_bind_pos_landmark.npy and per-topo mean bind_pose, reports
numerical stats, and writes:
  - matplotlib frontal+side scatter: blue=mean, green=per-id   (PNG)
  - Maya import script: blue=mean, green=per-id                (PY, optional)

Usage:
    # Stats + matplotlib for a few representative ids
    python vis_per_id_bind_pos_landmark.py \
        --rig_path maya_rig/hybrid \
        --feat_dir nfs_features_seg \
        --ids ict_000 ict_005 m--20180226--0000--6674443--GHS \
        --out_dir maya_rig/hybrid/per_id_bind_pose_vis

    # Add Maya script
    python vis_per_id_bind_pos_landmark.py ... --maya
"""
import os
import sys
import argparse
import numpy as np

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, '..', '..')))
from utils.rig_loader import load_rig


_MAYA_TEMPLATE = '''"""Auto-generated by vis_per_id_bind_pos_landmark.py
Two skeleton hierarchies:
  - {prefix}_maya_mean  (BLUE):  per-topo mean bind_pos (Maya GT)
  - {prefix}_landmark   (GREEN): landmark-derived per-id bind_pos (Phase B GT)
"""
import maya.cmds as cmds


_MEAN_POS  = {mean_positions!r}
_PRED_POS  = {pred_positions!r}
_NAMES     = {joint_names!r}
_PARENTS   = {parent_names!r}
_PREFIX    = {prefix!r}


def _build(label, positions, color_rgb):
    grp = cmds.group(em=True, n=f'{{_PREFIX}}_{{label}}')
    for name, parent in zip(_NAMES, _PARENTS):
        jname = f'{{_PREFIX}}_{{label}}_{{name}}'
        if parent is None:
            cmds.select(grp)
        else:
            cmds.select(f'{{_PREFIX}}_{{label}}_{{parent}}')
        cmds.joint(p=positions[name], n=jname)
        cmds.setAttr(f'{{jname}}.overrideEnabled', 1)
        cmds.setAttr(f'{{jname}}.overrideColor', color_rgb)
    cmds.select(cl=True)
    return grp


def main():
    for _lbl in ('maya_mean', 'landmark'):
        _g = f'{{_PREFIX}}_{{_lbl}}'
        if cmds.objExists(_g):
            cmds.delete(_g)
    _build('maya_mean', _MEAN_POS, 6)    # blue
    _build('landmark',  _PRED_POS, 14)   # green
    print(f'Created: {{_PREFIX}}_maya_mean (blue)  +  {{_PREFIX}}_landmark (green)')


main()
'''


def _topo_for_id(id_name):
    if id_name.startswith('ict_'): return 'ict'
    if id_name.startswith('m--'):  return 'mf'
    if id_name.startswith('biwi_'):return 'biwi'
    return 'voca'


_TEMPLATE_CACHE = {}   # (dataset, data_basedir) → list[(V, faces, name)]


def _get_template_mesh(id_name, topo, data_basedir):
    """Look up per-id (V, faces) by id_name. Returns (None, None) on miss."""
    ds = {'ict': 'ict', 'mf': 'mf'}.get(topo)
    if ds is None:
        return None, None
    key = (ds, data_basedir)
    if key not in _TEMPLATE_CACHE:
        from extract_nfs_feat import load_templates_ict, load_templates_mf
        if ds == 'ict':
            _TEMPLATE_CACHE[key] = load_templates_ict()
        else:
            _TEMPLATE_CACHE[key] = load_templates_mf(data_basedir)
    for V, F_, n in _TEMPLATE_CACHE[key]:
        if n == id_name:
            return V, F_
    return None, None


def _write_obj(path, verts, faces):
    """Simple OBJ writer (1-indexed faces)."""
    with open(path, 'w') as f:
        for v in verts:
            f.write(f'v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n')
        for tri in faces:
            f.write(f'f {int(tri[0])+1} {int(tri[1])+1} {int(tri[2])+1}\n')


def _scatter_views(mean_pos, pred_pos, joint_names, save_path,
                   face_idx=None, point_size=18.0):
    """Frontal (XY) + Side (ZY) scatter, blue=mean, green=pred, with lines connecting same joint."""
    mean_pos = np.asarray(mean_pos)
    pred_pos = np.asarray(pred_pos)

    if face_idx is None:
        face_idx = list(range(len(joint_names)))
    F = np.asarray(face_idx, dtype=int)

    fig = plt.figure(figsize=(8, 4))

    # Frontal: x vs y
    ax = fig.add_subplot(1, 2, 1)
    ax.scatter(mean_pos[F, 0], mean_pos[F, 1], s=point_size, c='blue',
               edgecolors='k', linewidths=0.3, label='mean (per-topo GT)', zorder=10)
    ax.scatter(pred_pos[F, 0], pred_pos[F, 1], s=point_size, c='green',
               edgecolors='k', linewidths=0.3, label='per-id (landmark)', zorder=11)
    for j in F:
        ax.plot([mean_pos[j, 0], pred_pos[j, 0]],
                [mean_pos[j, 1], pred_pos[j, 1]],
                color='gray', linewidth=0.4, zorder=5)
    ax.set_aspect('equal'); ax.set_xlabel('x'); ax.set_ylabel('y')
    ax.set_title('Frontal (XY)')
    ax.legend(fontsize=7, loc='lower left')

    # Side: z vs y
    ax = fig.add_subplot(1, 2, 2)
    ax.scatter(mean_pos[F, 2], mean_pos[F, 1], s=point_size, c='blue',
               edgecolors='k', linewidths=0.3, zorder=10)
    ax.scatter(pred_pos[F, 2], pred_pos[F, 1], s=point_size, c='green',
               edgecolors='k', linewidths=0.3, zorder=11)
    for j in F:
        ax.plot([mean_pos[j, 2], pred_pos[j, 2]],
                [mean_pos[j, 1], pred_pos[j, 1]],
                color='gray', linewidth=0.4, zorder=5)
    ax.set_aspect('equal'); ax.set_xlabel('z'); ax.set_ylabel('y')
    ax.set_title('Side (ZY)')

    os.makedirs(os.path.dirname(save_path) or '.', exist_ok=True)
    plt.tight_layout()
    plt.savefig(save_path, dpi=200, bbox_inches='tight')
    plt.close(fig)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--rig_path', type=str, required=True)
    ap.add_argument('--feat_dir', type=str, default='nfs_features_seg')
    ap.add_argument('--ids',      nargs='+', required=True,
                    help='Identity names to visualize (e.g. ict_000, m--20180226--...)')
    ap.add_argument('--out_dir',  type=str, default='maya_rig/hybrid/per_id_bind_pose_vis')
    ap.add_argument('--active_joints_json', type=str,
                    default='maya_rig/hybrid/active_joints_manual.json',
                    help='Restrict scatter to face joints (cleaner view)')
    ap.add_argument('--maya',     action='store_true',
                    help='Also emit per-id Maya import script + per-id template .obj')
    ap.add_argument('--data_basedir', type=str, default='/data/sihun')
    args = ap.parse_args()

    rig = load_rig(args.rig_path, device='cpu')
    J = len(rig.joint_names)
    parent_names = []
    for p in rig.parent_idx.cpu().numpy().tolist():
        parent_names.append(None if p == -1 else rig.joint_names[int(p)])

    # Optional: face joint indices for cleaner scatter
    face_idx = None
    if args.active_joints_json and os.path.exists(args.active_joints_json):
        import json as _json
        with open(args.active_joints_json) as f:
            face_idx = _json.load(f)['face_joint_idx']

    os.makedirs(args.out_dir, exist_ok=True)

    print(f'─── Per-id bind_pose verification (Phase B GT) ───')
    print(f'rig: J={J}, face joints: {len(face_idx) if face_idx else J}')
    print(f'feat_dir: {args.feat_dir}')
    print(f'out_dir:  {args.out_dir}\n')

    for idn in args.ids:
        topo = _topo_for_id(idn)
        if topo not in rig.bind_pos_dict:
            print(f'[skip] {idn}: topo {topo} not in rig.bind_pos_dict'); continue

        per_id_path = os.path.join(args.feat_dir, f'{idn}_bind_pos_landmark.npy')
        if not os.path.exists(per_id_path):
            print(f'[skip] {idn}: {per_id_path} not found'); continue

        per_id  = np.load(per_id_path).astype(np.float32)              # [J, 3]
        mean_GT = rig.bind_pos_dict[topo].cpu().numpy().astype(np.float32)  # [J, 3]

        # Stats
        delta = per_id - mean_GT                                        # [J, 3]
        d_norm = np.linalg.norm(delta, axis=-1)                          # [J]
        F = np.array(face_idx) if face_idx else np.arange(J)
        print(f'[{idn}]  topo={topo}')
        print(f'  delta ||per_id - mean||:   '
              f'all-J min={d_norm.min():.4f}, mean={d_norm.mean():.4f}, max={d_norm.max():.4f}')
        print(f'                              '
              f'face-only  min={d_norm[F].min():.4f}, mean={d_norm[F].mean():.4f}, max={d_norm[F].max():.4f}')
        # Top-5 most shifted joints (face only)
        order = np.argsort(-d_norm[F])[:5]
        print(f'  top-5 shifted (face joints):')
        for k in order:
            j = int(F[k])
            print(f'    [{j:2d}] {rig.joint_names[j]:42s}  ||δ||={d_norm[j]:.4f}  '
                  f'δ=({delta[j,0]:+.3f}, {delta[j,1]:+.3f}, {delta[j,2]:+.3f})')

        # Matplotlib scatter
        png_path = os.path.join(args.out_dir, f'{idn}_bind_pos_vis.png')
        _scatter_views(mean_GT, per_id, rig.joint_names, png_path, face_idx=face_idx)
        print(f'  saved → {png_path}')

        # Maya script + OBJ
        if args.maya:
            mean_d = {n: mean_GT[i].tolist() for i, n in enumerate(rig.joint_names)}
            pred_d = {n: per_id[i].tolist()  for i, n in enumerate(rig.joint_names)}
            # Reorder joint creation by topological order so parents are built first
            # (rig may have parent_idx > self_idx after helper reparenting).
            _po = getattr(rig, 'process_order', None)
            if _po is not None:
                _po = _po.cpu().numpy().tolist()
            else:
                _po = list(range(len(rig.joint_names)))
            names_ordered   = [rig.joint_names[i] for i in _po]
            parents_ordered = [parent_names[i]    for i in _po]
            py = _MAYA_TEMPLATE.format(
                mean_positions=mean_d,
                pred_positions=pred_d,
                joint_names=names_ordered,
                parent_names=parents_ordered,
                prefix=idn.replace('--', '_').replace('-', '_'),
            )
            py_path = os.path.join(args.out_dir, f'{idn}_bind_pos_maya.py')
            with open(py_path, 'w') as f:
                f.write(py)
            print(f'  saved → {py_path}')

            # OBJ for the per-id mesh (for Maya import)
            V_id, faces_id = _get_template_mesh(idn, topo, args.data_basedir)
            if V_id is not None:
                obj_path = os.path.join(args.out_dir, f'{idn}_template.obj')
                _write_obj(obj_path, V_id, faces_id)
                print(f'  saved → {obj_path}')

        print()


if __name__ == '__main__':
    main()
