"""
export_pred_joints_maya.py — Export predicted joint positions as Maya-ready scripts.

Runs HLBS bind_pose_net forward for a given identity, then writes:
  - pred_joints_{ds}_{idx}.py     Maya Python script: creates joint hierarchy
                                   at predicted positions (also builds Maya-init
                                   copy for side-by-side comparison)
  - pred_joints_{ds}_{idx}.json   Raw data (name, parent, maya_pos, pred_pos, shift)
  - template_{ds}_{idx}.obj       Template mesh for importing alongside

Usage:
    python export_pred_joints_maya.py \
        --ckpt_dir ckpts_hlbs/2026-04-22-10-13-53-HLBS-FullPred-ict-jTrans-nrm0.1-Wsm0.01 \
        --epoch best \
        --datasets ict:0,mf:12

Then in Maya:
    1. File > Import the .obj
    2. Window > Script Editor > Python tab > run the .py file
    3. Two skeleton groups appear: '{ds}_{idx}_maya_init' (reference, blue) and
       '{ds}_{idx}_pred' (learned, green). Compare them.
"""
import os
import sys
import json
import argparse
import numpy as np
import yaml
import torch
import igl

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, '..', '..'))
sys.path.insert(0, _HERE)
sys.path.insert(0, _ROOT)
sys.path.insert(0, os.path.join(_ROOT, 'tools', 'vis'))  # vis_hlbs_weights_multi
from utils.rig_loader import load_rig
from models.hierarchical_lbs import HierarchicalLBS_FullPred
from vis_hlbs_weights_multi import load_template, load_nfs_feat_cached, extract_nfs_feat_online


_MAYA_TEMPLATE = '''"""Auto-generated by export_pred_joints_maya.py
Run inside Maya's Python script editor.
Creates two joint hierarchies:
  - {prefix}_gt   (BLUE):  per-id bind_pose GT (Phase B v3 cache) or per-topo
                           mean fallback — the supervision target the model
                           was trained against.
  - {prefix}_pred (GREEN): predicted by bind_pose_net

Args:  joints = [(name, parent_name_or_None, (x,y,z)), ...]  root-first order
"""
import maya.cmds as cmds


_GT_POS    = {maya_positions!r}
_PRED_POS  = {pred_positions!r}
_NAMES     = {joint_names!r}
_PARENTS   = {parent_names!r}
_PREFIX    = {prefix!r}


def _build(label, positions, color_rgb):
    grp_name = f'{{_PREFIX}}_{{label}}'
    if cmds.objExists(grp_name):
        cmds.delete(grp_name)
    grp = cmds.group(em=True, n=grp_name)
    for name, parent in zip(_NAMES, _PARENTS):
        jname = f'{{_PREFIX}}_{{label}}_{{name}}'
        if parent is None:
            cmds.select(grp)
        else:
            cmds.select(f'{{_PREFIX}}_{{label}}_{{parent}}')
        pos = positions[name]
        cmds.joint(p=pos, n=jname)
        cmds.setAttr(f'{{jname}}.overrideEnabled', 1)
        cmds.setAttr(f'{{jname}}.overrideColor', color_rgb)
    cmds.select(cl=True)
    return grp


def main():
    # Color indices: 6=blue, 14=green, 13=red
    _build('gt',   _GT_POS,   6)
    _build('pred', _PRED_POS, 14)
    print(f'Created: {{_PREFIX}}_gt (blue, per-id supervision target) + '
          f'{{_PREFIX}}_pred (green)')


main()
'''


def _write_maya_script(save_path, prefix, joint_names, parent_names,
                       maya_positions, pred_positions):
    # Positions dict keyed by joint name
    maya_dict = {n: list(p) for n, p in zip(joint_names, maya_positions)}
    pred_dict = {n: list(p) for n, p in zip(joint_names, pred_positions)}

    content = _MAYA_TEMPLATE.format(
        prefix=prefix,
        joint_names=joint_names,
        parent_names=parent_names,
        maya_positions=maya_dict,
        pred_positions=pred_dict,
    )
    with open(save_path, 'w') as f:
        f.write(content)


def _write_obj(save_path, verts, faces):
    with open(save_path, 'w') as f:
        for v in verts:
            f.write(f'v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n')
        for tri in faces:
            f.write(f'f {tri[0]+1} {tri[1]+1} {tri[2]+1}\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ckpt_dir', type=str, required=True)
    ap.add_argument('--epoch', type=str, default='best')
    ap.add_argument('--device', type=str, default='cuda:0')
    ap.add_argument('--datasets', type=str, default='ict:0,mf:12',
                    help='Comma-separated ds:idx pairs')
    args = ap.parse_args()

    device = torch.device(args.device)

    opts_path = os.path.join(args.ckpt_dir, 'train_opts.yml')
    with open(opts_path) as f:
        opts = yaml.safe_load(f)

    rig = load_rig(opts['rig_path'])
    model = HierarchicalLBS_FullPred(
        rig=rig,
        in_dim_exp=12,
        hid_dim=opts.get('hid_dim', 128),
        num_layers=opts.get('num_layers', 4),
        device=str(device),
        use_joint_trans=opts.get('use_joint_trans', False),
        dfn_skin=opts.get('dfn_skin', False),
        dfn_bind=opts.get('dfn_bind', False),
        dfn_exp=opts.get('dfn_exp', False),
        nfs_feat_dim=256 if opts.get('nfs_feat_dir') else 0,
        nfs_concat=opts.get('nfs_concat', False),
        adain_pos_norm=opts.get('adain_pos_norm', False),
        freeze_bind_pose=opts.get('freeze_bind_pose', False),
        use_gmm_hybrid=opts.get('use_gmm_hybrid', False),
        init_log_sigma=opts.get('init_log_sigma', -1.2),
    ).to(device)

    ckpt_path = os.path.join(args.ckpt_dir, f'model_hlbs_{args.epoch}.pth')
    model.load_state_dict(torch.load(ckpt_path, map_location=device), strict=False)
    model.eval()
    print(f'Loaded {ckpt_path}')

    # Joint hierarchy info (common across identities)
    J = model.num_joints
    joint_names = list(model.joint_names)
    parent_idx  = model.parent_idx.detach().cpu().numpy().tolist()
    parent_names = [joint_names[p] if p >= 0 else None for p in parent_idx]
    bind_pos_mean = model.bind_pos_target.detach().cpu().numpy()   # [J, 3] per-topo mean fallback

    # Per-id bind_pose GT cache dir (Phase B v3). When a per-id .npy exists, it's
    # the supervision target the model was trained against — use it as the BLUE
    # reference (otherwise fall back to per-topology mean).
    per_id_dir = opts.get('per_id_bind_pose_dir') or opts.get('nfs_feat_dir') or 'nfs_features_seg'

    ds_specs = [(s.split(':')[0], int(s.split(':')[1])) for s in args.datasets.split(',')]
    out_dir = os.path.join(args.ckpt_dir, f'pred_joints_{args.epoch}_maya')
    os.makedirs(out_dir, exist_ok=True)

    for ds_key, id_idx in ds_specs:
        verts, faces, id_name = load_template(ds_key, id_idx)
        normals = igl.per_vertex_normals(verts, faces).astype(np.float32)
        src_v = torch.tensor(verts,   dtype=torch.float32, device=device).unsqueeze(0)
        src_n = torch.tensor(normals, dtype=torch.float32, device=device).unsqueeze(0)

        print(f'\n── {ds_key}:{id_idx} ({id_name}, V={verts.shape[0]}) ──')

        # Resolve GT reference: per-id cache > per-topology mean
        per_id_path = os.path.join(per_id_dir, f'{id_name}_bind_pos_landmark.npy')
        if os.path.exists(per_id_path):
            gt_pos = np.load(per_id_path).astype(np.float32)       # [J, 3]
            gt_source = f'per-id cache ({per_id_path})'
        else:
            gt_pos = bind_pos_mean.copy()
            gt_source = f'per-topology mean (no {per_id_path})'
        print(f'  GT reference: {gt_source}')

        nfs_feat = None
        nfs_feat_dir = opts.get('nfs_feat_dir')
        if nfs_feat_dir:
            nfs_feat = load_nfs_feat_cached(id_name, nfs_feat_dir, device=str(device))
            if nfs_feat is None:
                nfs_feat = extract_nfs_feat_online(verts, faces, device=str(device))
            if nfs_feat is not None:
                nfs_feat = nfs_feat.unsqueeze(0)

        with torch.no_grad():
            skin_input, _adain = model._prepare_feat(src_v, src_n, nfs_feat)
            if model.freeze_bind_pose:
                pred_pos = model.bind_pos_target.unsqueeze(0).expand(src_v.shape[0], -1, -1)
            else:
                _, pred_pos = model._get_bind_pose(skin_input, adain_input=_adain)

        pred_np = pred_pos[0].cpu().numpy()                        # [J, 3]
        shifts  = np.linalg.norm(pred_np - gt_pos, axis=-1)        # [J] pred ↔ GT

        prefix = f'{ds_key}_{id_idx:03d}'
        # (a) Maya python script — BLUE = per-id GT (or fallback mean), GREEN = pred
        py_path = os.path.join(out_dir, f'pred_joints_{prefix}.py')
        _write_maya_script(py_path, prefix, joint_names, parent_names,
                           gt_pos.tolist(), pred_np.tolist())

        # (b) JSON dump
        json_path = os.path.join(out_dir, f'pred_joints_{prefix}.json')
        with open(json_path, 'w') as f:
            json.dump({
                'id_name': id_name,
                'gt_source': gt_source,
                'joint_names': joint_names,
                'parent_names': parent_names,
                'gt_positions': gt_pos.tolist(),
                'pred_positions': pred_np.tolist(),
                'shift_from_gt': shifts.tolist(),
            }, f, indent=2)

        # (c) OBJ of template
        obj_path = os.path.join(out_dir, f'template_{prefix}.obj')
        _write_obj(obj_path, verts, faces)

        # Print top-shifted joints
        print(f'  saved: {py_path}')
        print(f'         {json_path}')
        print(f'         {obj_path}')
        order = np.argsort(-shifts)
        print(f'  top-10 shifted joints (pred ↔ GT):')
        for j in order[:10]:
            print(f'    [{j:2d}] {joint_names[j]:38s}  shift={shifts[j]:.4f}  '
                  f'gt=({gt_pos[j,0]:+.2f},{gt_pos[j,1]:+.2f},{gt_pos[j,2]:+.2f})  '
                  f'pred=({pred_np[j,0]:+.2f},{pred_np[j,1]:+.2f},{pred_np[j,2]:+.2f})')

    print(f'\nDone. Output dir: {out_dir}')
    print('\nIn Maya:')
    print('  1. File > Import > template_*.obj')
    print('  2. Window > General Editors > Script Editor > Python tab')
    print('  3. Open pred_joints_*.py and Execute (Ctrl+Enter)')
    print('  → Blue = Maya init skeleton, Green = predicted skeleton')


if __name__ == '__main__':
    main()
