config: configs/train.yml
rig_path: maya_rig/hybrid
topo_key: ict
num_identities: 13
hid_dim: 128
num_layers: 4
lambda_W_reg: 0.0001
lambda_t_reg: 0.0001
lambda_neu: 1.0
lambda_W_smooth: 0.01
freeze_adapt: false
use_joint_trans: true
smooth_delta_W: 0
smooth_delta_W_alpha: 0.5
lambda_normal: 0.1
lambda_curvature: 0.0
full_prediction: true
init_phase_epochs: 20
init_hold_epochs: 0
init_mode: anneal
lambda_init: 0.0
lambda_bind_reg: 1.0
lambda_helper_residual: 0.01
lambda_cross_cyclic: 0.0
lambda_mirror: 0.1
helper_joints_json: maya_rig/hybrid/helper_joints_v1.json
lambda_rwc: 0.0
rwc_alpha: 0.5
rwc_adaptive: false
rwc_topologies: ict
lambda_hier: 0.0
hier_margin: 0.0
lambda_dist: 0.0
freeze_bind_pose: false
bind_pose_mode: net
joint_anchors_npy: null
joint_offsets_npy: null
attn_temperature_init: 0.1
bind_pos_cache_dir: null
use_gmm_hybrid: true
use_geodesic_gauss: true
geo_dist_dir: null
per_id_bind_pose_dir: nfs_features_seg
lambda_cross_retarget: 0.0
cross_pair_iden_vecs: data/ICT_live_100/iden_vecs.npy
cross_pair_length: 0
subsample_ratio: 0.0
subsample_mode: mix4
subsample_mix3_alpha: 99.0
subsample_ratio_min: 0.1
subsample_ratio_max: 0.5
subsample_contour_r0: 0.05
subsample_contour_r1: 0.2
subsample_contour_alpha: 4.0
subsample_contour_kind: point
subsample_region_falloff: 0.1
normal_knn_k: 16
init_log_sigma: -1.2
gmm_mode: residual
residual_scale: 4.0
sigma_targets_npy: maya_rig/hybrid/sigma_targets.npy
lambda_sigma_reg: 0.1
lambda_net_center: 0.05
use_helpers: 1
active_joints_json: maya_rig/hybrid/active_joints_manual.json
face_mask_r0: 1.0
face_mask_r1: 2.25
dfn_skin: false
dfn_bind: false
dfn_exp: false
nfs_feat_dir: nfs_features_seg
nfs_concat: true
nfs_on_cpu: false
adain_pos_norm: true
nfs_ckpt: null
target: gt
smooth_n_iter: 0
batch_size: 8
lr: 0.0001
max_epoch: 500
save_interval: 50
eval_iter: 25
val_every: 10
seed: 42
sc_step: 1000000
sc_gamma: 0.5
lambda_vert: 1.0
num_workers: 0
no_t_mask: false
use_data0: false
use_data1: false
use_data2: true
use_data3: false
curriculum: false
curriculum_epochs: 30
data_toggle: false
no_fullhead: false
ckpt: null
start_epoch: 0
continue_ckpt: false
data_basedir: /data/sihun
log_dir: ckpts_hlbs/2026-05-14-14-02-03-HLBS-FullPred-ict-jTrans-nrm0.1-Wsm0.01
tb: false
debug: false
vis_frames: config/vis_frames.yml
version: 10
use_strain: false
strain_dim: 1
use_lbs: false
use_lbs_joint_center: false
no_use_translation: false
use_laplacian: false
data_rand_trans: false
data_rand_scale: false
window_size: 1
use_decimate: false
use_data9: false
