# Test args
device: 'cuda:0'
seed: 42
n_sampling: False

# check point
continue_ckpt: False
save_interval: 50

in_type: 1
out_type: 1

# optimizer
lr : 0.0002
max_epoch: 500
start_epoch: 0

# scheduler
sc_step: 10
sc_gamma: 0.95

# loss
lambda_mvc: 1.0
lambda_align: 2.0
lambda_p2f: 0.1
lambda_norm: 0.1
lambda_vert: 1.0

batch_size: 8

# Data directory
log_dir: "./ckpts_CBD"

ckpt: ''

is_train: True
tb: True

data_rand_scale: False
data_rand_trans: True

debug: False